### PR TITLE
Serve request paths with trailing slashes

### PR DESCRIPTION
**Pull request by erikzeneco**
#### Summary

Respond to requests that have trailing slashes or double slashes as if they didn't have them.

The python cosmosdb client sends trailing slashes and double slashes in the urls of its requests. This caused a redirect to be sent back by cosmium. (http-router setting RedirectTrailingSlash) The redirect is not handled by python client and results in errors.

Modifications are intended to be as much as possible in seperate files and methods.  (Instead of duplicating all paths and changing path to resource parsing logic in authenticator middleware.)

The router is created with the RemoveExtraSlash setting. The correct routes are copied with a slash appended, and a trailing slash stripping middleware so authentication middlewares resource parsing still works.

### CODE REVIEW

**Comment by pikami** [comment]
I've gone trough your PR and I found a way to do this that I like more. Instead of registering multiple routes I just used a middleware to rewrite the URL.
I've pushed the changes to a new branch [erikzeneco/serve_request_paths_with_trailing_slashes](https://github.com/pikami/cosmium/tree/erikzeneco/serve_request_paths_with_trailing_slashes), please check it out and see if it works with your python client. If it works I will merge it, if not please give me some python code example that I could use to reproduce the issue on my side.
Thanks.

**Comment by erikzeneco** [comment]
Great, your solution also works with the real python client. Thanks for the quick reply and fixes.

**Comment by erikzeneco** [comment]
[erikzeneco/serve_request_paths_with_trailing_slashes](https://github.com/pikami/cosmium/tree/erikzeneco/serve_request_paths_with_trailing_slashes), works as expected.

My faulty test caused 404 error instead of cosmium.

**Comment by pikami** [comment]
Merged, thanks for the help

**Pull request merged**
